import { $ } from './core.js';

export class AlarmController {
  constructor(storage){ this.storage=storage; this.alarms=this.storage.get('alarms',[]); this.snoozeMinutes=this.storage.get('snoozeMinutes',5); this.ringing=null; }
  init(){ $('addAlarmButton').onclick=()=>this.add(); $('alarmList').addEventListener('click',(e)=>this.handle(e)); $('snoozeAlarmButton').onclick=()=>this.snooze(); $('stopAlarmButton').onclick=()=>this.stop(); $('snoozeMinutes')?.addEventListener('change',()=>{this.snoozeMinutes=Math.max(1,+$('snoozeMinutes').value||5);this.storage.set('snoozeMinutes',this.snoozeMinutes);}); if($('snoozeMinutes'))$('snoozeMinutes').value=this.snoozeMinutes; this.render(); setInterval(()=>this.check(),1000); }
  selectedDays(){ return [...document.querySelectorAll('.weekday-button.active')].map((b)=>+b.dataset.day); }
  add(){ const time=$('alarmTime').value||'07:00',label=$('alarmLabel').value.trim()||'アラーム',days=this.selectedDays(),sound=$('alarmSound')?.value||'beep'; this.alarms.push({id:crypto.randomUUID?.()||String(Date.now()),time,label,days,sound,enabled:true,lastKey:null}); this.save();this.render(); }
  handle(e){ const action=e.target.closest('[data-alarm-action]'); if(!action)return; const a=this.alarms.find((x)=>x.id===action.dataset.id); if(!a)return; if(action.dataset.alarmAction==='toggle')a.enabled=!a.enabled; if(action.dataset.alarmAction==='delete')this.alarms=this.alarms.filter((x)=>x.id!==a.id); if(action.dataset.alarmAction==='edit'){ $('alarmTime').value=a.time;$('alarmLabel').value=a.label;document.querySelectorAll('.weekday-button').forEach((b)=>b.classList.toggle('active',a.days.includes(+b.dataset.day)));if($('alarmSound'))$('alarmSound').value=a.sound||'beep';this.alarms=this.alarms.filter((x)=>x.id!==a.id);} this.save();this.render(); }
  check(){ const now=new Date(); const hh=String(now.getHours()).padStart(2,'0'),mm=String(now.getMinutes()).padStart(2,'0'),key=`${now.toDateString()}-${hh}:${mm}`; this.alarms.forEach((a)=>{ if(!a.enabled||a.time!==`${hh}:${mm}`||a.lastKey===key)return; if(a.days.length&& !a.days.includes(now.getDay()))return; a.lastKey=key; this.ring(a); }); this.save(); }
  ring(a){ this.ringing=a; $('ringingAlarmLabel').textContent=a.label;$('ringingAlarmTime').textContent=a.time;$('snoozeAlarmButton').textContent=`${this.snoozeMinutes}分スヌーズ`;$('alarmOverlay').classList.remove('hidden'); this.beep(a.sound); if(navigator.vibrate)navigator.vibrate([300,150,300,150,300]); }
  beep(sound){ try{ const ctx=new (window.AudioContext||window.webkitAudioContext)(); const osc=ctx.createOscillator(),gain=ctx.createGain(); osc.type=sound==='soft'?'sine':'square'; osc.frequency.value=sound==='high'?980:sound==='soft'?440:700; gain.gain.value=.08; osc.connect(gain).connect(ctx.destination); osc.start(); setTimeout(()=>{osc.stop();ctx.close();},1200);}catch{} }
  snooze(){ if(!this.ringing)return; const d=new Date(Date.now()+this.snoozeMinutes*60000); this.alarms.push({id:crypto.randomUUID?.()||String(Date.now()),time:`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`,label:`${this.ringing.label}（スヌーズ）`,days:[],sound:this.ringing.sound,enabled:true,lastKey:null,oneShot:true}); this.stop();this.save();this.render(); }
  stop(){ $('alarmOverlay').classList.add('hidden'); if(this.ringing?.oneShot)this.alarms=this.alarms.filter((x)=>x.id!==this.ringing.id); this.ringing=null;this.save();this.render(); }
  save(){this.storage.set('alarms',this.alarms);}
  render(){ const box=$('alarmList'); $('alarmCount').textContent=`${this.alarms.length}件`; box.innerHTML=this.alarms.length?this.alarms.map((a)=>`<article class="alarm-item ${a.enabled?'':'alarm-off'}"><div><p class="alarm-item-time">${a.time}</p><p class="alarm-item-label">${this.escape(a.label)}</p><p class="alarm-item-days">${a.days.length?a.days.map((d)=>'日月火水木金土'[d]).join('・'):'1回'} · ${a.sound||'beep'}</p></div><div class="alarm-actions"><button class="secondary-button small-button" data-alarm-action="toggle" data-id="${a.id}">${a.enabled?'OFF':'ON'}</button><button class="secondary-button small-button" data-alarm-action="edit" data-id="${a.id}">編集</button><button class="danger-button small-button" data-alarm-action="delete" data-id="${a.id}">削除</button></div></article>`).join(''):'<p class="empty-message">アラームはまだありません</p>'; }
  escape(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML;}
}
