import { $, TimeFormatter } from './core.js';

export class ConverterController {
  constructor(cities){ this.cities=cities; this.formatter=new TimeFormatter(); this.compareZones=[]; }
  init(){ this.from=$('convertFrom');this.to=$('convertTo');this.date=$('convertDate');this.time=$('convertTime');this.result=$('convertResult'); const options=this.cities.all().map((c)=>`<option value="${c.zone}">${c.ja}</option>`).join(''); this.from.innerHTML=options;this.to.innerHTML=options;this.from.value='Asia/Tokyo';this.to.value='Europe/London'; const now=new Date();this.date.value=now.toISOString().slice(0,10);this.time.value='18:00'; $('convertButton').onclick=()=>this.convert(); $('naturalConvertButton').onclick=()=>this.naturalConvert(); $('addCompareCityButton').onclick=()=>this.addCompare(); $('compareCitySelect').innerHTML=options; this.compareZones=['Asia/Tokyo','Europe/London','America/New_York']; this.renderCompare(); }
  convert(){ const instant=this.formatter.localDateToInstant(this.date.value,this.time.value,this.from.value); const f=this.formatter.format(instant,this.to.value,false,true); const a=this.cities.find(this.from.value),b=this.cities.find(this.to.value); this.result.innerHTML=`<b>${a?.ja} ${this.date.value} ${this.time.value}</b><span>→</span><strong>${b?.ja} ${f.date} ${f.time}</strong>`; }
  naturalConvert(){ const raw=$('naturalConvertInput').value.trim(); const m=raw.match(/(.+?)(\d{1,2}):(\d{2}).*?(?:→|から|は)(.+)$/); if(!m){this.result.textContent='例：東京18:00→ロンドン のように入力してね';return;} const from=this.cities.resolve(m[1]),to=this.cities.resolve(m[4]); if(!from||!to){this.result.textContent='都市名を読み取れなかったよ';return;} this.from.value=from.zone;this.to.value=to.zone;this.time.value=`${String(+m[2]).padStart(2,'0')}:${m[3]}`;this.convert(); }
  addCompare(){ const z=$('compareCitySelect').value;if(!this.compareZones.includes(z)&&this.compareZones.length<4)this.compareZones.push(z);this.renderCompare(); }
  renderCompare(){ const box=$('compareGrid'); const now=new Date(); box.innerHTML=this.compareZones.map((z)=>{const c=this.cities.find(z),f=this.formatter.format(now,z,false,true);return `<article class="compare-card"><button class="compare-remove" data-zone="${z}">×</button><b>${c?.ja}</b><strong>${f.time}</strong><span>${f.date}</span><small>${this.formatter.offsetLabel(z)}</small></article>`;}).join(''); box.querySelectorAll('.compare-remove').forEach((b)=>b.onclick=()=>{this.compareZones=this.compareZones.filter((z)=>z!==b.dataset.zone);this.renderCompare();}); }
}
