import { $ } from './core.js';

export class TimerController {
  constructor(storage, notifier=null){ this.storage=storage; this.notifier=notifier; this.timers=this.storage.get('timers',[]); this.history=this.storage.get('timerHistory',[]); }
  init(){ $('addMultiTimerButton')?.addEventListener('click',()=>this.addFromInputs()); document.querySelectorAll('.quick-button').forEach((b)=>b.addEventListener('click',()=>this.add(+b.dataset.minutes*60000,`${b.dataset.minutes}分タイマー`))); $('multiTimerList')?.addEventListener('click',(e)=>this.handle(e)); this.render(); this.interval=setInterval(()=>this.tick(),250); }
  addFromInputs(){ const min=+$('timerMinutes').value||0, sec=+$('timerSeconds').value||0, label=$('timerLabel')?.value.trim()||'タイマー'; const ms=(min*60+sec)*1000; if(ms>0)this.add(ms,label); }
  add(ms,label){ this.timers.push({id:crypto.randomUUID?.()||String(Date.now()+Math.random()),label,initial:ms,remaining:ms,running:true,end:Date.now()+ms}); this.save(); this.render(); }
  remaining(t){ return t.running?Math.max(0,t.end-Date.now()):t.remaining; }
  format(ms){ const s=Math.ceil(Math.max(0,ms)/1000); return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; }
  tick(){ let changed=false; this.timers.forEach((t)=>{ if(t.running&&this.remaining(t)<=0){t.running=false;t.remaining=0;this.history.unshift({label:t.label,finishedAt:Date.now(),duration:t.initial});changed=true;if(navigator.vibrate)navigator.vibrate([180,80,180]);this.notifier?.notify('タイマー終了',`${t.label}の時間です`,{tag:`timer-${t.id}`,url:'./?view=timer'});} }); if(changed){this.history=this.history.slice(0,20);this.save();} this.renderTimes(); }
  handle(e){ const b=e.target.closest('button[data-action]'); if(!b)return; const t=this.timers.find((x)=>x.id===b.dataset.id); if(!t)return; if(b.dataset.action==='pause'){ if(t.running){t.remaining=this.remaining(t);t.running=false;}else if(t.remaining>0){t.running=true;t.end=Date.now()+t.remaining;} } if(b.dataset.action==='reset'){t.running=false;t.remaining=t.initial;} if(b.dataset.action==='delete'){this.timers=this.timers.filter((x)=>x.id!==t.id);} this.save();this.render(); }
  save(){ this.storage.set('timers',this.timers);this.storage.set('timerHistory',this.history); }
  render(){ const box=$('multiTimerList'); if(!box)return; box.innerHTML=this.timers.length?this.timers.map((t)=>`<article class="timer-item" data-timer-id="${t.id}"><div><b>${this.escape(t.label)}</b><p class="timer-item-time">${this.format(this.remaining(t))}</p></div><div class="timer-item-actions"><button class="secondary-button small-button" data-action="pause" data-id="${t.id}">${t.running?'停止':'再開'}</button><button class="secondary-button small-button" data-action="reset" data-id="${t.id}">戻す</button><button class="danger-button small-button" data-action="delete" data-id="${t.id}">削除</button></div></article>`).join(''):'<p class="empty-message">タイマーはまだありません</p>'; this.renderHistory(); }
  renderTimes(){ this.timers.forEach((t)=>{const el=document.querySelector(`[data-timer-id="${t.id}"] .timer-item-time`);if(el)el.textContent=this.format(this.remaining(t));}); }
  renderHistory(){ const box=$('timerHistory'); if(!box)return; box.innerHTML=this.history.length?this.history.map((h)=>`<div class="history-row"><span>${this.escape(h.label)}</span><span>${Math.round(h.duration/60000)}分</span></div>`).join(''):'<p class="empty-message">履歴はまだありません</p>'; }
  escape(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML;}
}
